### ISSUE TITLE
Windows rgdal/GDAL WFS driver

### ISSUE THREAD

**Issue by rsbivand** [rOpenGov/rwfs#14]
I've opened an [issue](https://github.com/rwinlib/gdal2/issues/5) on the appropriate repo.

**Comment by jlehtoma** [comment]
Great, thanks!

**Comment by jlehtoma** [comment]
WFS driver is now enable in [`gdal2`](github.com/rwinlib/gdal2/issues/5). Probably still takes a little while to hit CRAN.

**Comment by jlehtoma** [comment]
Driver has been in CRAN for a while, closing this issue.
