### ISSUE TITLE
Improving caching?

### ISSUE THREAD

**Issue by jlehtoma** [rOpenGov/rwfs#3]
~~In, fact doesn't seem to work at all.~~

**Comment by jlehtoma** [comment]
Caching works, but the cache is specific to a `WFSCachedClient` object. With the creation of a new object, the cache is invalidated. More broad functionality would be to have a global cache, in which `digest(URL)` would be used as a key. This way cache would be shared with objects and even sessions.

**Comment by torsti** [comment]
Re: persistent cache: What about [CRAN's policy](https://cran.r-project.org/web/packages/policies.html) being against writing to the filesystem, especially without user confirmation?

**Comment by jlehtoma** [comment]
I remember having this discussion somewhere before, but I don't remember what the outcome was... Enabling persistent caching would be an opt-in thing, which I think is conceptually the same thing as the user writing on the disk. I.e. it's not done without the user knowing about it. Then again `saveGML()` method can already be used. I'll come back to this later, will keep it like it is for now.
