### ISSUE TITLE
Remove need for ogr2ogr translation

### ISSUE THREAD

**Issue by jlehtoma** [rOpenGov/rwfs#5]
Currently, there are two ways getting the data from the data source:

1. Create a class inheriting from `rwfs::WFSStreamingRequest`, implement method `getDataSource()` and read data directly from data source using `rgdal::readOGR()` (actually twice: first for reading the layers, then the actual data). No caching is possible.
1. Create a class inheriting from `rwfs::WFSCachingRequest` or instantiate it directly. Read (download) data only once from the data source and save to a temp directory. Use `ogr2ogr -explodecollections` to locally translate the (GML) data. Read the translated data in using `rgdal::readOGR()`. Within the lifetime of an instance (object), the responses are cached.

### Original problem

The original reason for having the extra `ogr2ogr`-step is the following:

> Due to limited support for WFS 2.x in the rgdal package, which the rwfs package depends on, data in > WFS 2.x is accessible only via downloading the data first and thus no streaming can be used (at least > in some services).

This has (hopefully) changed with more recent (>= 2.0.0) versions of `GDAL`, meaning that the  `ogr2ogr`-step could in theory be removed. Many users, particularly on Windows, have had trouble in getting `ogr2ogr` to work. 

### Making ogr2ogr optional

If the `ogr2ogr` step is not required (now in [`rwfs::WFSCachingClient$getLayer()`](https://github.com/rOpenGov/rwfs/blob/master/R/WFSClient.R#L241)), then effectively modifying `rwfs::WFSCachingClient` should be enough. Instead of completely removing the step, the functionality should be retained for cases where it is still needed. For caching, it is always necessary to download the data. Downloading the data also removes the need the get the data twice as in streaming.

**Comment by jlehtoma** [comment]
The implementation is now in `develop` branch, I'll merge it to `master` once I get a chance to test it on a Windows machine.

**Comment by jlehtoma** [comment]
Note that the current implementation (when skipping `ogr2ogr`) doesn't create column `fid` in the Spatial*DataFrame. This may break things, so create that column manually somehow.

**Comment by jlehtoma** [comment]
Manual creation of `fid` implemented in 02b19874f9225c3ba0362ec93e2441af1dbf94b3.

**Comment by jlehtoma** [comment]
@ouzor : Is there any chance you could test WFS functions you have in `gisfin` against the development version of `rwfs` (install from branch `develop`)? Would be nice to see if things still work. FWICT, examples in `fmi` seem to work okay, but would be nice to test the `WFSStreamingClient` as well.

**Comment by jlehtoma** [comment]
For the most part, tests in https://github.com/rOpenGov/gisfin/blob/GeoserverHelFi/inst/extras/test_new_geoservers.R work although there's something funky going on with how layers are defined.

**Comment by jlehtoma** [comment]
Until further notice, everything looks good. Closing this issue.

**Comment by ouzor** [comment]
Sorry I missed the request. Discussion continuing here: https://github.com/rOpenGov/gisfin/issues/33
