### ISSUE TITLE
Update README and installation instructions 

### ISSUE THREAD

**Issue by jlehtoma** [rOpenGov/rwfs#8]

**Comment by jlehtoma** [comment]
`rgdal` installation instructions should be placed in a wiki somewhere, but this can be done later.

**Comment by ouzor** [comment]
It may be that installing rgdal is now more straighforward than before, and
there's no need for separate instructions. To test this, one would need
fresh test machines with no GDAL etc. installed. I have one Windows at work
where I could test this. This is also relevant for the gisfin package.

**Comment by jlehtoma** [comment]
- For Windows, it's straightforward for sure as the package is installed as a binary.
- For Mac, [the kyngchaos binaries](http://www.kyngchaos.com/software/frameworks) are still the way to go.
- With Linux, the package is compiled from source, so certain libraries are still needed as dependencies.

The major improvement here is that since `ogr2ogr` is not strictly required anymore, setting up the system paths is no longer needed. This has been a major pain at least on Windows.
